import { Issue, ChatMessage } from "./types";

export const INITIAL_ISSUES: Issue[] = [
  {
    id: "ISS-001",
    title: "Main St Pothole",
    category: "Infrastructure",
    severity: "High",
    status: "In Progress",
    location: "242 Main St, Downtown District",
    coordinates: "40.7128° N, 74.0060° W",
    timeAgo: "2 hours ago",
    description: "This issue describes a significant pavement failure approximately 12 inches in diameter. UrbanVoice AI has cross-referenced this with 3 other reports in the same block. Based on traffic density data for Main St, this pothole presents a high risk for tire damage and cyclist safety. Repairs are estimated to take 2 hours once dispatched.",
    imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuCQ_OEqJ2MQNKw66F9oLMlF_ztfzKyDuxH96DTiYMSuFzBZCXsh6FnbNQJf_qMxFlMop31HJ4eRjyrA9vxs2Vbrc5qAb2AhxX1s-b2g1Kb0MG2S5-Etcbdlhiy_UYUoneZi9KXHOknXjn3q3cVgPtIMn8p1yg-G7zr2KmNLJHpScsJ9LlS762OwvCx7qgKFS_CXcqudWSLbDESEAA-WjUNIU8SUxMb9msGpUcakEaJmOvn701-wrlRETfghTFO8ufa66F9Zpl7fWymT",
    votes: 12,
    followed: false,
    assignedDept: "Road Maintenance",
    officer: {
      name: "David K.",
      avatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuD_6JmRxr4IPuPZKTTgQrc6JAMwBWHBaJMthAiO5kgzVFGzMScORUTXTKQal_-PFZs0vvHMdJFAzMrx_tIfwnw-suj-J9SjdsSf5Xgpp98qaDEyLVCvRBFTBfZpsCEgXrhFB0yRkh7lRdQxEDZanu2UKb3dYIV8FokSSC9Ve2c8GUAmYaxtuGdu44zT3z4lTUpmFeJTNZPzMXV94yOO2UtTXSF9BL77tzDScll_gY2hhLsyJ3GzNw-scAzKefL5GoOYk44Ze3GE2b2z",
      role: "Maintenance Supervisor",
      verified: true,
    },
    slaCountdown: "14:02:45",
    slaPercentage: 65,
    comments: [
      {
        id: "c1",
        user: "Sarah Jenkins",
        avatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuCiKlZ4mJIbQ9Y2ScmeDf0XwTgim0CI_1WcHVYJPm6sPhskqBrGpMI07WDj7RVlczeFpYo0Pe9H2wy1voCKXyjSldODMCHdUojY6ivQmw8zvqbYI543XeZ0V3KT9lcQRE-fbVNYJ0RhzbWDzHv6b3XkPqPkXIHx0-95DePoT4EbKkB8v51HGBPJR7K0jPnCzgfiB_u3T6TheRTm-wxfSOHKRs3HtxIvZaPsagmRfB6YwVt_POOVnmQpBc-UyjPLFADAaa4xt2wW3O9Q",
        text: "Almost lost a tire on this last night. Glad it's being addressed!",
        timeAgo: "1 hour ago",
      }
    ],
    timeline: [
      {
        id: "t1",
        title: "Work Order Assigned",
        description: "Dispatched to Road Maintenance Crew #4.",
        timeAgo: "2 hours ago",
        icon: "Wrench",
      },
      {
        id: "t2",
        title: "Issue Verified",
        description: "Civic AI confirmed report via satellite image analysis.",
        timeAgo: "5 hours ago",
        icon: "Cpu",
      },
      {
        id: "t3",
        title: "Initial Report",
        description: "Citizen report submitted via UrbanVoice Mobile.",
        timeAgo: "6 hours ago",
        icon: "Megaphone",
      }
    ],
  },
  {
    id: "ISS-002",
    title: "Cracked Pavement",
    category: "Infrastructure",
    severity: "High",
    status: "Pending",
    location: "5th Ave & 23rd St, Manhattan",
    coordinates: "40.7411° N, 73.9897° W",
    timeAgo: "2 hours ago",
    description: "A detailed photo of a damaged city sidewalk with cracked pavement in a residential neighborhood. Natural daylight lighting, professional focus on textures, urban maintenance theme, high resolution.",
    imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuDMKLsc3hxhlfo-awflR7WTWJZ0uoMoCDQb2V4EEMRbLl8_6iUxiYjvrS9hbQ8l1b4peqMFhRTH7-cWrfZbOyrusIydq2vmKb73QvGBBB1I5sGXeb2xcKdr513aN7zgmLeuHne2J8mOLzFFxkKPyOJp-WVnE6cxBXrixh9qKXgu0smM31JNlsx6JYoUXY-RSEPc7E_VcBvhKadpXkf69Aqwidi7NRlSBLZz2qUsGRB719oGqHXY5HPxbgCDiCzUkgCxnse7VuC5RBfe",
    votes: 8,
    followed: false,
    assignedDept: "Sidewalk Division",
    officer: {
      name: "Marcus Aurelius",
      avatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuDeFmuchrTGVgj_x_b5V-bwFsizno5bs4zMssCXhmBDR5L8ZwFkHqVFZ21ukVNCjLC2VDW7p6mn3OwnSaSLJWDjGG8wGaycHnhQMntVB-FhNzYdw7JErcFIvVWbayk35m0oLAbH1N55rRMIR1GXcHCrqx6HYs0dR-OS3C2JWk-93vqjdEbtsPP2MRsUxALfoDM6YfE40Uz-30cyRoLjU2kE6auLURP_gGYM8hVYVWER2mhUNDVQO8GSymUd-hC3fy78U1T7M6xGqyof",
      role: "Pavement Specialist",
      verified: true,
    },
    slaCountdown: "23:45:00",
    slaPercentage: 80,
    comments: [],
    timeline: [
      {
        id: "t1",
        title: "Report Registered",
        description: "Citizen logged pavement cracking warning.",
        timeAgo: "2 hours ago",
        icon: "Megaphone",
      }
    ],
  },
  {
    id: "ISS-003",
    title: "Broken Streetlight",
    category: "Utilities",
    severity: "Medium",
    status: "In Progress",
    location: "Lexington Ave & 42nd St",
    coordinates: "40.7516° N, 73.9754° W",
    timeAgo: "5 hours ago",
    description: "Close up photo of a broken streetlight in a modern city during twilight. Creates unsafe walking conditions for pedestrian crossing walkways.",
    imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuAKPVUKuIQrjkv3bSOwfTk3Zq4tmPCeEdpLeiagTEjRbA_febV38Z6vr1uJAIR95GayCOtTgCH1vddHhKgxQKa8GU5FIm_E7ko6_FsgyncmIn3X8JGAvarXs_qlnyGYm9DAwst8DU2gwZb4zg1AK9GaRi90nZ-5qDa7Y6rAEJkySSEIZSmQeWoWGJzL-IAaHkyO5hQZKCBungw0uoy0UX5AnH3_nDpCOofObbTyn4cjDhRE8U8IdRfH3UvjkX2FHjaTiXyg3c0BJ9-p",
    votes: 14,
    followed: true,
    assignedDept: "Electrical Services",
    officer: {
      name: "Clara S.",
      avatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuADFk2DXUGNz06ZQHwf-n0-ggg_yy5TZYkYsV1bJ94ECOSuY2yVf1xlFKjXe2OpK7eAkChTgIghYJkF-zcOS_VezSFjxJQXB2haru_ocs9N78yVnj6SHselK4gXz6wswLgIYhxTnKRKNBAgbaO5ROWbBdqQQOlmrkxZVnmnqhRnzpxgB5SQaVo2Ag5LrPl8c8-HR3a_jiO6CFPgSZ6dXjhQaQRitDHyuaKDQSiGnnnT3nDeOKZkeLeOdVHTmf0EwC9rZFN4cntV5cea",
      role: "Chief Grid Electrician",
      verified: true,
    },
    slaCountdown: "01:45:00",
    slaPercentage: 35,
    comments: [],
    timeline: [
      {
        id: "t1",
        title: "Dispatch Crew Sent",
        description: "Electrical maintenance crew dispatched to replace bulb #L-492.",
        timeAgo: "1 hour ago",
        icon: "Wrench",
      },
      {
        id: "t2",
        title: "Initial Log",
        description: "Report registered by resident at dusk.",
        timeAgo: "5 hours ago",
        icon: "Megaphone",
      }
    ],
  },
  {
    id: "ISS-004",
    title: "Pothole in Ward 4",
    category: "Infrastructure",
    severity: "High",
    status: "Pending",
    location: "West End Primary Road",
    coordinates: "40.7289° N, 74.0012° W",
    timeAgo: "12 mins ago",
    description: "Severe road damage affecting traffic flow near West End Primary. Vehicles are swerving to avoid depth and risking head-on collisions during peak school drop-off hours.",
    imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuCQ_OEqJ2MQNKw66F9oLMlF_ztfzKyDuxH96DTiYMSuFzBZCXsh6FnbNQJf_qMxFlMop31HJ4eRjyrA9vxs2Vbrc5qAb2AhxX1s-b2g1Kb0MG2S5-Etcbdlhiy_UYUoneZi9KXHOknXjn3q3cVgPtIMn8p1yg-G7zr2KmNLJHpScsJ9LlS762OwvCx7qgKFS_CXcqudWSLbDESEAA-WjUNIU8SUxMb9msGpUcakEaJmOvn701-wrlRETfghTFO8ufa66F9Zpl7fWymT",
    votes: 24,
    followed: false,
    assignedDept: "Road Maintenance",
    officer: {
      name: "David K.",
      avatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuD_6JmRxr4IPuPZKTTgQrc6JAMwBWHBaJMthAiO5kgzVFGzMScORUTXTKQal_-PFZs0vvHMdJFAzMrx_tIfwnw-suj-J9SjdsSf5Xgpp98qaDEyLVCvRBFTBfZpsCEgXrhFB0yRkh7lRdQxEDZanu2UKb3dYIV8FokSSC9Ve2c8GUAmYaxtuGdu44zT3z4lTUpmFeJTNZPzMXV94yOO2UtTXSF9BL77tzDScll_gY2hhLsyJ3GzNw-scAzKefL5GoOYk44Ze3GE2b2z",
      role: "Maintenance Supervisor",
      verified: true,
    },
    slaCountdown: "47:48:00",
    slaPercentage: 99,
    comments: [],
    timeline: [
      {
        id: "t1",
        title: "Report Opened",
        description: "High-priority category identified by UrbanVoice AI.",
        timeAgo: "12 mins ago",
        icon: "Cpu",
      }
    ],
  },
  {
    id: "ISS-005",
    title: "Overflowing Bin at Park",
    category: "Sanitation",
    severity: "Low",
    status: "In Progress",
    location: "Central Park East Entrance",
    coordinates: "40.7712° N, 73.9625° W",
    timeAgo: "5 hours ago",
    description: "Trash collection missed at Central Park East entrance. Bin is overflowing onto the walkway attracting pests.",
    imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuDgupP_y-drxeA4OpugIddqZw3BG-djqdzuDKCWXUFjvdloO7BcUhVmPibcLJMvlXpYAHCdHQImJ8ArA3-1MSfRPLGlGZ63b7f5cmdL2MCWPpLczBBfV14cinwwfFI9AoHPZmLU8WinirKLnOMnsOOILhQBTpUt55tXpPOJOcjag0qx3ChkpAUHM93DNGIgJtBoZ7k9vWAJ1jnYz38jZXONE3M9CiZIEhz6w3rRWFEA-udjxKKDdrDxWyRa4gCTSXfmv0b2-d2qrocn",
    votes: 45,
    followed: false,
    assignedDept: "Sanitation Dept",
    officer: {
      name: "Marcus Aurelius",
      avatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuDeFmuchrTGVgj_x_b5V-bwFsizno5bs4zMssCXhmBDR5L8ZwFkHqVFZ21ukVNCjLC2VDW7p6mn3OwnSaSLJWDjGG8wGaycHnhQMntVB-FhNzYdw7JErcFIvVWbayk35m0oLAbH1N55rRMIR1GXcHCrqx6HYs0dR-OS3C2JWk-93vqjdEbtsPP2MRsUxALfoDM6YfE40Uz-30cyRoLjU2kE6auLURP_gGYM8hVYVWER2mhUNDVQO8GSymUd-hC3fy78U1T7M6xGqyof",
      role: "Operations Supervisor",
      verified: true,
    },
    slaCountdown: "04:20:12",
    slaPercentage: 40,
    comments: [],
    timeline: [
      {
        id: "t1",
        title: "Dispatched Sanitation Crew",
        description: "Assigned to Park Sanitation Route 12.",
        timeAgo: "2 hours ago",
        icon: "Wrench",
      }
    ],
  },
  {
    id: "ISS-006",
    title: "Fallen Branch on Bike Path",
    category: "Landscaping",
    severity: "Medium",
    status: "Resolved",
    location: "Northbound Bike Lane near 12th St",
    coordinates: "40.7302° N, 74.0041° W",
    timeAgo: "7 hours ago",
    description: "Large oak branch blocking the northbound bike lane near 12th Street intersection. Cyclists have to enter vehicle traffic lane to bypass.",
    imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuDgupP_y-drxeA4OpugIddqZw3BG-djqdzuDKCWXUFjvdloO7BcUhVmPibcLJMvlXpYAHCdHQImJ8ArA3-1MSfRPLGlGZ63b7f5cmdL2MCWPpLczBBfV14cinwwfFI9AoHPZmLU8WinirKLnOMnsOOILhQBTpUt55tXpPOJOcjag0qx3ChkpAUHM93DNGIgJtBoZ7k9vWAJ1jnYz38jZXONE3M9CiZIEhz6w3rRWFEA-udjxKKDdrDxWyRa4gCTSXfmv0b2-d2qrocn",
    votes: 19,
    followed: false,
    assignedDept: "Parks & Recreation",
    officer: {
      name: "Marcus Aurelius",
      avatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuDeFmuchrTGVgj_x_b5V-bwFsizno5bs4zMssCXhmBDR5L8ZwFkHqVFZ21ukVNCjLC2VDW7p6mn3OwnSaSLJWDjGG8wGaycHnhQMntVB-FhNzYdw7JErcFIvVWbayk35m0oLAbH1N55rRMIR1GXcHCrqx6HYs0dR-OS3C2JWk-93vqjdEbtsPP2MRsUxALfoDM6YfE40Uz-30cyRoLjU2kE6auLURP_gGYM8hVYVWER2mhUNDVQO8GSymUd-hC3fy78U1T7M6xGqyof",
      role: "Parks Supervisor",
      verified: true,
    },
    slaCountdown: "00:00:00",
    slaPercentage: 0,
    comments: [],
    timeline: [
      {
        id: "t1",
        title: "Cleared and Closed",
        description: "Branch chopped and removed from path.",
        timeAgo: "30 mins ago",
        icon: "CheckCircle",
      },
      {
        id: "t2",
        title: "Work Order Approved",
        description: "Parks and Rec dispatch on site.",
        timeAgo: "4 hours ago",
        icon: "Wrench",
      }
    ],
  }
];

export const INITIAL_MESSAGES: ChatMessage[] = [
  {
    id: "msg-1",
    sender: "copilot",
    text: "I've detected a cluster of 4 drainage issues in **Ward 7** reported over the last 24 hours. This coincides with the recent storm data.\n\nWould you like a summary of the impact or should I draft a priority alert for the District Council?",
    timestamp: "10:42 AM",
    status: "complete",
    isInsight: true,
  },
  {
    id: "msg-2",
    sender: "user",
    text: "Yes, please provide a summary and show them on my current map view.",
    timestamp: "10:43 AM",
  }
];
